import type { KeywordIdea } from './keywords';

export const vtcBaseKeywordIdeas: KeywordIdea[] = [
  { keyword: 'vtc nice', intent: 'local' },
  { keyword: 'chauffeur privé cannes', intent: 'local' },
  { keyword: 'vtc monaco', intent: 'local' },
  { keyword: "transfert aéroport nice", intent: 'local' },
  { keyword: "navette aéroport nice côte d'azur", intent: 'local' },
  { keyword: "chauffeur privé côte d'azur", intent: 'local' },
  { keyword: 'vtc nice cannes', intent: 'local' },
  { keyword: 'transfert nice monaco', intent: 'local' },
  { keyword: "chauffeur privé nice aéroport", intent: 'local' },
  { keyword: 'vtc cannes monaco', intent: 'local' },
  { keyword: 'prix vtc nice', intent: 'transactional' },
  { keyword: 'tarif chauffeur privé nice', intent: 'transactional' },
  { keyword: 'réserver vtc nice', intent: 'transactional' },
  { keyword: 'chauffeur privé événement cannes', intent: 'transactional' },
  { keyword: 'vtc festival cannes', intent: 'local' },
  { keyword: 'chauffeur privé grand prix monaco', intent: 'local' },
  { keyword: 'vtc business nice', intent: 'transactional' },
  { keyword: "chauffeur privé tourisme côte d'azur", intent: 'informational' },
  { keyword: "visite côte d'azur avec chauffeur", intent: 'informational' },
  { keyword: 'excursion chauffeur privé nice', intent: 'informational' },
  { keyword: 'transfert gare nice ville', intent: 'local' },
  { keyword: 'vtc antibes', intent: 'local' },
  { keyword: 'chauffeur privé saint tropez', intent: 'local' },
  { keyword: 'vtc menton', intent: 'local' },
  { keyword: 'comment réserver un vtc à nice', intent: 'informational' },
  { keyword: 'différence vtc taxi nice', intent: 'informational' },
  { keyword: "vtc luxe côte d'azur", intent: 'transactional' },
  { keyword: 'chauffeur privé berline nice', intent: 'transactional' },
  { keyword: 'van avec chauffeur nice', intent: 'transactional' },
  { keyword: 'vtc 24h nice', intent: 'transactional' },
  { keyword: 'chauffeur privé nuit nice', intent: 'transactional' },
  { keyword: "transfert hôtel aéroport nice", intent: 'local' },
  { keyword: "vtc mariage côte d'azur", intent: 'transactional' },
  { keyword: 'chauffeur privé déplacement professionnel nice', intent: 'transactional' },
  { keyword: 'vtc longue distance nice', intent: 'transactional' },
  { keyword: 'navette aéroport nice cannes', intent: 'other' },
  { keyword: 'transfert aéroport nice monaco', intent: 'other' },
  { keyword: 'prix vtc nice cannes', intent: 'other' },
  { keyword: 'réserver chauffeur privé nice', intent: 'other' },
  { keyword: 'vtc grand prix monaco', intent: 'other' },
  { keyword: "chauffeur tourisme côte d'azur", intent: 'other' },
  { keyword: 'chauffeur privé aéroport nice', intent: 'other' },
  { keyword: 'vtc saint tropez', intent: 'other' },
  { keyword: "chauffeur privé mariage côte d'azur", intent: 'other' },
  { keyword: 'vtc juan les pins', intent: 'other' },
  { keyword: 'transfert nice cannes', intent: 'other' },
  { keyword: 'chauffeur privé visite eze', intent: 'other' },
  { keyword: 'devis vtc nice', intent: 'other' },
  { keyword: 'vtc grasse', intent: 'other' },
  { keyword: 'transfert port cannes', intent: 'other' },
  { keyword: 'chauffeur privé nice monaco', intent: 'other' },
  { keyword: 'vtc berline nice', intent: 'other' },
  { keyword: 'différence taxi vtc nice', intent: 'other' },
  { keyword: "chauffeur privé van côte d'azur", intent: 'other' },
  { keyword: 'vtc villefranche sur mer', intent: 'other' }
];
