import type { V1GeneratorInput } from './types';

export interface V1PagePlanEntry extends V1GeneratorInput {
  slug: string;
}

// Plan de pages ECOFUNDRIVE VTC Côte d'Azur
// 28 pages FR + 12 pages EN, alignées avec seoLanguages du profil vtcCoteAzurTestSite

export const vtcCoteAzurPagePlan: V1PagePlanEntry[] = [
  // ───────────── FR - pages globales / autorité ─────────────
  {
    slug: 'fr/chauffeur-prive-cote-d-azur',
    keyword: "chauffeur privé côte d'azur",
    language: 'fr',
    category: 'transactional',
    location: "Côte d'Azur (Marseille, Saint-Tropez, Nice, Cannes, Monaco)",
    authority: true,
    mode: 'A',
    wordcount: 2000,
  },
  {
    slug: 'fr/vtc-luxe-cote-d-azur',
    keyword: "vtc luxe côte d'azur",
    language: 'fr',
    category: 'transactional',
    location: "Côte d'Azur (Nice, Cannes, Monaco)",
    authority: true,
    mode: 'A',
    wordcount: 2400,
  },

  // ───────────── FR - pages villes principales ─────────────
  {
    slug: 'fr/vtc-nice',
    keyword: 'vtc nice',
    language: 'fr',
    category: 'local',
    location: 'Nice',
    authority: false,
    mode: 'standard',
    wordcount: 1700,
  },
  {
    slug: 'fr/chauffeur-prive-cannes',
    keyword: 'chauffeur privé cannes',
    language: 'fr',
    category: 'local',
    location: 'Cannes',
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/vtc-monaco',
    keyword: 'vtc monaco',
    language: 'fr',
    category: 'local',
    location: 'Monaco',
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/vtc-antibes',
    keyword: 'vtc antibes',
    language: 'fr',
    category: 'local',
    location: 'Antibes',
    authority: false,
    mode: 'standard',
    wordcount: 1600,
  },
  {
    slug: 'fr/vtc-saint-tropez',
    keyword: 'vtc saint tropez',
    language: 'fr',
    category: 'local',
    location: 'Saint-Tropez',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/vtc-juan-les-pins',
    keyword: 'vtc juan les pins',
    language: 'fr',
    category: 'local',
    location: 'Juan-les-Pins',
    authority: false,
    mode: 'standard',
    wordcount: 1500,
  },
  {
    slug: 'fr/vtc-villefranche-sur-mer',
    keyword: 'vtc villefranche sur mer',
    language: 'fr',
    category: 'local',
    location: 'Villefranche-sur-Mer',
    authority: false,
    mode: 'standard',
    wordcount: 1800,
  },
  {
    slug: 'fr/vtc-grasse',
    keyword: 'vtc grasse',
    language: 'fr',
    category: 'local',
    location: 'Grasse',
    authority: false,
    mode: 'standard',
    wordcount: 1800,
  },
  {
    slug: 'fr/vtc-menton',
    keyword: 'vtc menton',
    language: 'fr',
    category: 'local',
    location: 'Menton',
    authority: false,
    mode: 'standard',
    wordcount: 1800,
  },

  // ───────────── FR - transferts aéroport / gares ─────────────
  {
    slug: 'fr/transfert-aeroport-nice',
    keyword: "transfert aéroport nice",
    language: 'fr',
    category: 'local',
    location: 'Nice Aéroport',
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/navette-aeroport-nice-cote-d-azur',
    keyword: "navette aéroport nice côte d'azur",
    language: 'fr',
    category: 'local',
    location: 'Nice Aéroport / Côte d\'Azur',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/transfert-aeroport-nice-cannes',
    keyword: 'navette aéroport nice cannes',
    language: 'fr',
    category: 'local',
    location: 'Nice ⇄ Cannes',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/transfert-aeroport-nice-monaco',
    keyword: 'transfert aéroport nice monaco',
    language: 'fr',
    category: 'local',
    location: 'Nice ⇄ Monaco',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/chauffeur-prive-aeroport-nice',
    keyword: 'chauffeur privé aéroport nice',
    language: 'fr',
    category: 'local',
    location: 'Nice Aéroport',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/transfert-gare-nice-ville',
    keyword: 'transfert gare nice ville',
    language: 'fr',
    category: 'local',
    location: 'Nice (gare / centre-ville)',
    authority: false,
    mode: 'standard',
    wordcount: 1800,
  },

  // ───────────── FR - usages spécifiques / occasions ─────────────
  {
    slug: 'fr/vtc-longue-distance-nice',
    keyword: 'vtc longue distance nice',
    language: 'fr',
    category: 'transactional',
    location: 'Nice / France / Europe',
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/vtc-mariage-cote-d-azur',
    keyword: "vtc mariage côte d'azur",
    language: 'fr',
    category: 'transactional',
    location: "Côte d'Azur (Nice, Cannes, Saint-Tropez)",
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/chauffeur-prive-mariage-cote-d-azur',
    keyword: "chauffeur privé mariage côte d'azur",
    language: 'fr',
    category: 'transactional',
    location: "Côte d'Azur (Nice, Cannes, Monaco)",
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/chauffeur-prive-evenement-cannes',
    keyword: 'chauffeur privé événement cannes',
    language: 'fr',
    category: 'transactional',
    location: 'Cannes (événements, congrès)',
    authority: false,
    mode: 'standard',
    wordcount: 1800,
  },
  {
    slug: 'fr/vtc-festival-cannes',
    keyword: 'vtc festival cannes',
    language: 'fr',
    category: 'transactional',
    location: 'Cannes (Festival du Film)',
    authority: false,
    mode: 'standard',
    wordcount: 2100,
  },
  {
    slug: 'fr/chauffeur-prive-grand-prix-monaco',
    keyword: 'chauffeur privé grand prix monaco',
    language: 'fr',
    category: 'transactional',
    location: 'Monaco (Grand Prix F1)',
    authority: false,
    mode: 'standard',
    wordcount: 2100,
  },
  {
    slug: 'fr/vtc-business-nice',
    keyword: 'vtc business nice',
    language: 'fr',
    category: 'transactional',
    location: 'Nice (business / corporate)',
    authority: false,
    mode: 'standard',
    wordcount: 2100,
  },
  {
    slug: 'fr/chauffeur-prive-tourisme-cote-d-azur',
    keyword: "chauffeur privé tourisme côte d'azur",
    language: 'fr',
    category: 'informational',
    location: "Côte d'Azur", 
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/visite-cote-d-azur-avec-chauffeur',
    keyword: "visite côte d'azur avec chauffeur",
    language: 'fr',
    category: 'informational',
    location: "Côte d'Azur", 
    authority: false,
    mode: 'standard',
    wordcount: 2200,
  },
  {
    slug: 'fr/excursion-chauffeur-prive-nice',
    keyword: 'excursion chauffeur privé nice',
    language: 'fr',
    category: 'informational',
    location: 'Nice et alentours',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },

  // ───────────── FR - prix / réservation ─────────────
  {
    slug: 'fr/prix-vtc-nice',
    keyword: 'prix vtc nice',
    language: 'fr',
    category: 'transactional',
    location: 'Nice',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'fr/reserver-vtc-nice',
    keyword: 'réserver vtc nice',
    language: 'fr',
    category: 'transactional',
    location: 'Nice',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },

  // ───────────── EN - core French Riviera pages ─────────────
  {
    slug: 'en/private-driver-french-riviera',
    keyword: 'private driver french riviera',
    language: 'en',
    category: 'transactional',
    location: 'French Riviera (Nice, Cannes, Monaco)',
    authority: true,
    mode: 'A',
    wordcount: 2000,
  },
  {
    slug: 'en/luxury-chauffeur-french-riviera',
    keyword: 'luxury chauffeur french riviera',
    language: 'en',
    category: 'transactional',
    location: 'French Riviera (Nice, Cannes, Monaco)',
    authority: true,
    mode: 'A',
    wordcount: 2300,
  },

  // ───────────── EN - city pages ─────────────
  {
    slug: 'en/private-driver-nice',
    keyword: 'private driver nice',
    language: 'en',
    category: 'transactional',
    location: 'Nice',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/private-driver-cannes',
    keyword: 'private driver cannes',
    language: 'en',
    category: 'transactional',
    location: 'Cannes',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/private-driver-monaco',
    keyword: 'private driver monaco',
    language: 'en',
    category: 'transactional',
    location: 'Monaco',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/private-driver-saint-tropez',
    keyword: 'private driver saint tropez',
    language: 'en',
    category: 'transactional',
    location: 'Saint-Tropez',
    authority: false,
    mode: 'standard',
    wordcount: 1650,
  },

  // ───────────── EN - airport / business / occasions ─────────────
  {
    slug: 'en/nice-airport-transfer',
    keyword: 'nice airport transfer',
    language: 'en',
    category: 'transactional',
    location: 'Nice Airport',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/nice-airport-transfer-cannes',
    keyword: 'nice airport transfer cannes',
    language: 'en',
    category: 'transactional',
    location: 'Nice ⇄ Cannes',
    authority: false,
    mode: 'standard',
    wordcount: 1900,
  },
  {
    slug: 'en/nice-airport-transfer-monaco',
    keyword: 'nice airport transfer monaco',
    language: 'en',
    category: 'transactional',
    location: 'Nice ⇄ Monaco',
    authority: false,
    mode: 'standard',
    wordcount: 1900,
  },
  {
    slug: 'en/business-chauffeur-nice',
    keyword: 'business chauffeur nice',
    language: 'en',
    category: 'transactional',
    location: 'Nice (business / corporate)',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/long-distance-private-driver-nice',
    keyword: 'long distance private driver nice',
    language: 'en',
    category: 'transactional',
    location: 'Nice / long distance',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
  {
    slug: 'en/wedding-chauffeur-french-riviera',
    keyword: 'wedding chauffeur french riviera',
    language: 'en',
    category: 'transactional',
    location: 'French Riviera (Nice, Cannes, Saint-Tropez)',
    authority: false,
    mode: 'standard',
    wordcount: 2000,
  },
];
